linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - errors
      - github.com/pkg/errors
      - github.com/sirupsen/logrus
      - github.com/tehsphinx/dbg
      - flag
      - github.com/bmizerany/assert
  dupl:
    threshold: 150
  funlen:
    lines: 70
    statements: 40
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(gitlab.gostudent.cloud)
  gocyclo:
    min-complexity: 20
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  lll:
    line-length: 150
  maligned:
    suggest-new: true
  nakedret:
    max-func-lines: 6
  revive:
    rules:
      - name: argument-limit
        severity: warning
        disabled: false
        arguments: [5]

linters:
  enable-all: true
  disable:
    - cyclop
    - dupl
    - exhaustivestruct
    - exhaustruct
    - gocognit
    - godot
    - godox
    - gofumpt
    - golint
    - gomoddirectives
    # - gomnd
    - interfacer
    - ireturn
    - maintidx
    - maligned
    - nlreturn
    - paralleltest
    - scopelint
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    # - whitespace
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - gochecknoglobals
        - gocritic
        - gocyclo
        - gosec
        - prealloc
        - unparam
    - text: "Using the variable on range scope `tt` in function literal"
      linters:
        - scopelint

  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

    # govet: shadowing is.I instance in sub test.
    - declaration of "asrt" shadows declaration

    # gocritic: log.Fatal does not exit in our case
    - log.Fatal will exit
